#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("BestWeatherEver.Android.Resource", IsApplication=true)]

namespace BestWeatherEver.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cloudy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int day_rain = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int fog = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int partly_cloudy = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int rain = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int snow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sun = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int thermometer = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int thunder = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int wind = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int degreeLabel = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int imageView1 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int imageView2 = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int locationTextView = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int weatherImageView = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int weatherLabel = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int windLabel = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
